"""
The Ada Voice Layer. See docs/ARCHITECTURE_BIBLE.md Part 4A.3.

HARD RULE, not a style guideline: Ada's register ("I know" / "I suspect" /
"I recommend checking") is a DETERMINISTIC function of confidence_level.
It must never be freely generated by a language model and merely hoped to
match the underlying evidence strength - that would let a confident-sounding
sentence get produced from weak evidence, which is exactly the failure mode
Design Principle 1 (no score without evidence) exists to prevent.

Any prompt that generates Ada's natural-language output MUST call
`register_for_confidence()` first and be constrained to phrase the finding
in that register - never left to freely decide its own hedging language.
"""

from enum import Enum


class AdaRegister(str, Enum):
    KNOWS = "knows"                # confidence_level >= 90 - direct, declarative
    SUSPECTS = "suspects"          # 60-89 - hedged, must name the evidence
    RECOMMENDS_CHECKING = "recommends_checking"  # < 60 - never asserts, only flags


def register_for_confidence(confidence_level: int) -> AdaRegister:
    if not 0 <= confidence_level <= 100:
        raise ValueError("confidence_level must be between 0 and 100")
    if confidence_level >= 90:
        return AdaRegister.KNOWS
    if confidence_level >= 60:
        return AdaRegister.SUSPECTS
    return AdaRegister.RECOMMENDS_CHECKING


REGISTER_PROMPT_FRAMING = {
    AdaRegister.KNOWS: (
        "State this directly and declaratively. You have strong evidence. "
        "Do not hedge."
    ),
    AdaRegister.SUSPECTS: (
        "Hedge this claim explicitly (e.g. 'I suspect...', 'this looks like...'). "
        "You must name the specific evidence behind the suspicion."
    ),
    AdaRegister.RECOMMENDS_CHECKING: (
        "Do not assert this as true. Frame it only as something worth a human "
        "checking (e.g. 'worth reviewing...', 'recommend a back-check on...')."
    ),
}


def build_ada_utterance(finding_description: str, confidence_level: int) -> dict:
    """
    Returns the structured input for whatever LLM call renders Ada's final
    sentence - never the sentence itself. The generating prompt must include
    REGISTER_PROMPT_FRAMING[register] as a hard constraint, not a suggestion.
    """
    register = register_for_confidence(confidence_level)
    return {
        "finding": finding_description,
        "confidence_level": confidence_level,
        "register": register.value,
        "framing_instruction": REGISTER_PROMPT_FRAMING[register],
    }


# ---------------------------------------------------------------------------
# Deterministic renderers — LLM-free fallback path.
#
# build_ada_utterance() feeds an LLM that phrases the finding within its
# register. These renderers produce a fully deterministic sentence from the
# same register mapping, for surfaces that don't (yet) run an LLM call —
# e.g. the scorecard summary line — so the register rule holds even with no
# model in the loop.
# ---------------------------------------------------------------------------

_OPENERS = {
    AdaRegister.KNOWS: "I know",
    AdaRegister.SUSPECTS: "I suspect",
    AdaRegister.RECOMMENDS_CHECKING: "I recommend checking whether",
}


def render_finding(description: str, confidence_level: int) -> dict:
    """One finding, phrased in the register its confidence earns."""
    register = register_for_confidence(confidence_level)
    clause = description.strip().rstrip(".")
    clause = clause[0].lower() + clause[1:] if clause else clause
    return {
        "register": register.value,
        "text": f"{_OPENERS[register]} {clause}.",
        "confidence_level": confidence_level,
    }


def render_scorecard_summary(
    fraud_risk: str,
    confidence_level: int,
    recommended_action: str,
    top_finding_description: str | None,
) -> dict:
    """
    One-line scorecard summary. Length follows the finding (Bible 4A.7).
    A scorecard with no citable finding never asserts (Design Principle 1):
    it drops to the recommends_checking register regardless of confidence.
    """
    register = register_for_confidence(confidence_level)
    if fraud_risk == "low" and recommended_action == "none":
        base = {
            AdaRegister.KNOWS: "I know this interview is clean — no action needed",
            AdaRegister.SUSPECTS: "I suspect this interview is fine, though the evidence is thinner than usual",
            AdaRegister.RECOMMENDS_CHECKING: "I recommend checking whether this interview is fine — I don't have strong evidence either way",
        }[register]
        return {"register": register.value, "text": base + ".", "confidence_level": confidence_level}

    action_phrase = {
        "none": "no action is needed",
        "review_recording": "the recording should be reviewed",
        "conduct_backcheck": "a back-check should be conducted",
        "escalate": "this should be escalated",
    }.get(recommended_action, f"the recommended action is {recommended_action}")

    if top_finding_description:
        finding = render_finding(top_finding_description, confidence_level)
        return {
            "register": register.value,
            "text": f"{finding['text'].rstrip('.')}; {action_phrase}.",
            "confidence_level": confidence_level,
        }
    return {
        "register": AdaRegister.RECOMMENDS_CHECKING.value,
        "text": f"I recommend checking this interview manually — {action_phrase}, but no single finding stands out.",
        "confidence_level": confidence_level,
    }
