// Local report generator — produces a downloadable HTML file (Print → Save as PDF in any browser).
// For .xlsx we produce a CSV Blob.

export interface EnumeratorRow {
  name: string;
  submissions: number;
  pass: number;
  flag: number;
  reject: number;
}

export interface EngineRow {
  name: string;
  pass: number;
  flag: number;
  reject: number;
  total: number;
}

export interface ReportContext {
  projectName: string;
  orgName: string;
  submissionCount: number;
  passCount: number;
  flagCount: number;
  rejectCount: number;
  generatedBy: string;
  aiSummary?: string;
  aiThemes?: string[];
  aiQuotes?: string[];
  ifScore?: number;
  enumeratorRows?: EnumeratorRow[];
  engineRows?: EngineRow[];
  primaryColor?: string;
  accentColor?: string;
  brandFont?: string;
  brandFooter?: string;
  logoDataUrl?: string;
}

export function generateLocalReport(
  reportId: string,
  format: 'docx' | 'pptx' | 'xlsx',
  ctx: ReportContext
): { blob: Blob; filename: string } | null {
  const d = new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' });
  if (format === 'xlsx') return generateCsv(reportId, ctx, d);
  const html = generateHtml(reportId, ctx, d);
  const blob = new Blob([html], { type: 'text/html' });
  return { blob, filename: `${slug(ctx.projectName)}-${reportId}-report.html` };
}

function slug(s: string) {
  return s.replace(/\s+/g, '-').replace(/[^a-zA-Z0-9-]/g, '').toLowerCase();
}

function pct(n: number, total: number) {
  return total > 0 ? Math.round((n / total) * 100) : 0;
}

// ── CSV ───────────────────────────────────────────────────────────────────────

function generateCsv(reportId: string, ctx: ReportContext, date: string): { blob: Blob; filename: string } {
  const total = ctx.submissionCount || 1;
  const pass = pct(ctx.passCount, total);
  const flag = pct(ctx.flagCount, total);
  const rej  = pct(ctx.rejectCount, total);
  let rows: string[][] = [];

  if (reportId === 'technical') {
    rows = [['Engine Check', 'Pass Count', 'Flag Count', 'Reject Count', 'Total', 'Pass Rate']];
    (ctx.engineRows?.length
      ? ctx.engineRows
      : [{ name: 'GPS Accuracy', pass: ctx.passCount, flag: ctx.flagCount, reject: ctx.rejectCount, total },
         { name: 'Interview Duration', pass: ctx.passCount, flag: ctx.flagCount, reject: ctx.rejectCount, total },
         { name: 'Image Quality', pass: ctx.passCount, flag: ctx.flagCount, reject: ctx.rejectCount, total }]
    ).forEach(e => rows.push([e.name, String(e.pass), String(e.flag), String(e.reject), String(e.total), pct(e.pass, e.total || 1) + '%']));
  } else if (reportId === 'enumerator') {
    rows = [['Enumerator', 'Submissions', 'Pass', 'Flag', 'Reject', 'Pass Rate', 'Tier']];
    (ctx.enumeratorRows || []).forEach(e => {
      const t = e.submissions || 1;
      const p = pct(e.pass, t);
      const tier = p >= 85 ? 'Excellent' : p >= 70 ? 'Good' : p >= 55 ? 'Needs Coaching' : 'At Risk';
      rows.push([e.name, String(e.submissions), String(e.pass), String(e.flag), String(e.reject), p + '%', tier]);
    });
  } else {
    rows = [
      ['Metric', 'Value'],
      ['Project', ctx.projectName], ['Organisation', ctx.orgName], ['Generated', date],
      ['Total Submissions', String(ctx.submissionCount)],
      ['Pass', `${ctx.passCount} (${pass}%)`],
      ['Flagged', `${ctx.flagCount} (${flag}%)`],
      ['Rejected', `${ctx.rejectCount} (${rej}%)`],
      ['Generated By', ctx.generatedBy],
    ];
    if (ctx.ifScore !== undefined) rows.push(['Intent Fidelity Index', String(ctx.ifScore) + '/100']);
  }

  const csv = rows.map(r => r.map(c => `"${String(c).replace(/"/g, '""')}"`).join(',')).join('\n');
  return { blob: new Blob([csv], { type: 'text/csv' }), filename: `${slug(ctx.projectName)}-${reportId}.csv` };
}

// ── HTML ──────────────────────────────────────────────────────────────────────

function generateHtml(reportId: string, ctx: ReportContext, date: string): string {
  const total  = ctx.submissionCount || 1;
  const passP  = pct(ctx.passCount,   total);
  const flagP  = pct(ctx.flagCount,   total);
  const rejP   = pct(ctx.rejectCount, total);

  const P  = ctx.primaryColor  || '#2463EB';
  const A  = ctx.accentColor   || '#7C3AED';
  const F  = ctx.brandFont
    ? `'${ctx.brandFont}', Inter, 'Helvetica Neue', Arial, sans-serif`
    : "Inter, 'Helvetica Neue', Arial, sans-serif";
  const footerLine = ctx.brandFooter || 'Confidential · ResearchOS · FieldScore';

  const TITLES: Record<string, string> = {
    executive: 'Executive Summary',
    client:    'Client Delivery Report',
    technical: 'Technical Quality Report',
    enumerator:'Enumerator Performance Report',
  };
  const title = TITLES[reportId] || 'Field Research Report';

  // ── SVG donut chart ─────────────────────────────────────────────────────────
  function donut(pass: number, flag: number, rej: number, size = 140): string {
    const r = 52, cx = size / 2, cy = size / 2, stroke = 18;
    const circ = 2 * Math.PI * r;
    const passD  = (pass / 100)  * circ;
    const flagD  = (flag / 100)  * circ;
    const rejD   = (rej  / 100)  * circ;
    let offset = 0;
    const arc = (dashLen: number, color: string) => {
      const el = `<circle cx="${cx}" cy="${cy}" r="${r}" fill="none" stroke="${color}" stroke-width="${stroke}"
        stroke-dasharray="${dashLen} ${circ - dashLen}" stroke-dashoffset="${-(offset)}" transform="rotate(-90 ${cx} ${cy})"/>`;
      offset += dashLen;
      return el;
    };
    return `<svg width="${size}" height="${size}" viewBox="0 0 ${size} ${size}" xmlns="http://www.w3.org/2000/svg" style="flex-shrink:0">
      <circle cx="${cx}" cy="${cy}" r="${r}" fill="none" stroke="#F1F5F9" stroke-width="${stroke}"/>
      ${arc(passD,  '#059669')}
      ${arc(flagD,  '#D97706')}
      ${arc(rejD,   '#DC2626')}
      <text x="${cx}" y="${cy - 6}" text-anchor="middle" font-size="22" font-weight="800" fill="${P}" font-family="${F}">${pass}%</text>
      <text x="${cx}" y="${cy + 12}" text-anchor="middle" font-size="9" fill="#9CA3AF" font-family="${F}" letter-spacing="1">PASS RATE</text>
    </svg>`;
  }

  // ── Stacked bar ─────────────────────────────────────────────────────────────
  function stackedBar(pass: number, flag: number, rej: number, height = 10): string {
    return `<div style="display:flex;height:${height}px;border-radius:${height/2}px;overflow:hidden;background:#F1F5F9">
      ${pass > 0  ? `<div style="width:${pass}%;background:#059669"></div>`  : ''}
      ${flag > 0  ? `<div style="width:${flag}%;background:#D97706"></div>`  : ''}
      ${rej  > 0  ? `<div style="width:${rej}%;background:#DC2626"></div>`   : ''}
    </div>`;
  }

  // ── IFI gauge ───────────────────────────────────────────────────────────────
  function ifiGauge(score: number): string {
    const color = score >= 75 ? '#059669' : score >= 55 ? '#D97706' : '#DC2626';
    const label = score >= 75 ? 'Strong fidelity' : score >= 55 ? 'Moderate fidelity' : 'Low fidelity';
    const r = 48, cx = 70, cy = 64, stroke = 14;
    const circ = Math.PI * r; // half circle
    const filled = (score / 100) * circ;
    return `<svg width="140" height="78" viewBox="0 0 140 78" xmlns="http://www.w3.org/2000/svg">
      <path d="M ${cx - r} ${cy} A ${r} ${r} 0 0 1 ${cx + r} ${cy}" fill="none" stroke="#F1F5F9" stroke-width="${stroke}" stroke-linecap="round"/>
      <path d="M ${cx - r} ${cy} A ${r} ${r} 0 0 1 ${cx + r} ${cy}" fill="none" stroke="${color}" stroke-width="${stroke}" stroke-linecap="round"
        stroke-dasharray="${filled} ${circ - filled}"/>
      <text x="${cx}" y="${cy - 4}" text-anchor="middle" font-size="24" font-weight="800" fill="${color}" font-family="${F}">${score}</text>
      <text x="${cx}" y="${cy + 12}" text-anchor="middle" font-size="9" fill="#9CA3AF" font-family="${F}" letter-spacing=".5">/100</text>
      <text x="${cx}" y="${cy + 26}" text-anchor="middle" font-size="9" fill="${color}" font-family="${F}" font-weight="700">${label.toUpperCase()}</text>
    </svg>`;
  }

  // ── CSS ──────────────────────────────────────────────────────────────────────
  const css = `
    @page { size: A4; margin: 0; }
    @page :first { margin: 0; }
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: 'Inter', 'Helvetica Neue', Arial, sans-serif; background: white; color: #111827; font-size: 13.5px; line-height: 1.7; -webkit-print-color-adjust: exact; print-color-adjust: exact; }

    /* ── Cover page ── */
    .cover { min-height: 100vh; display: flex; flex-direction: column; position: relative; overflow: hidden;
      background: linear-gradient(145deg, ${P} 0%, ${A} 55%, #0A0E1A 100%); color: white; page-break-after: always; }

    /* Geometric decorations */
    .cover::before { content: ''; position: absolute; top: -120px; right: -120px; width: 480px; height: 480px;
      border-radius: 50%; background: rgba(255,255,255,.045); pointer-events: none; }
    .cover::after  { content: ''; position: absolute; bottom: 80px; left: -80px; width: 320px; height: 320px;
      border-radius: 50%; background: rgba(255,255,255,.03); pointer-events: none; }

    .cover-top { position: relative; z-index: 1; padding: 44px 56px 0; display: flex; justify-content: space-between; align-items: flex-start; }
    .cover-logo img { height: 40px; max-width: 160px; object-fit: contain; filter: brightness(0) invert(1); }
    .cover-logo-text { font-family: 'Plus Jakarta Sans', 'Inter', sans-serif; font-size: 14px; font-weight: 800; letter-spacing: 3.5px; color: rgba(255,255,255,.95); text-transform: uppercase; }
    .cover-logo-tag { font-size: 9.5px; color: rgba(255,255,255,.4); letter-spacing: 1.5px; margin-top: 5px; text-transform: uppercase; }
    .cover-type { font-size: 9.5px; font-weight: 700; letter-spacing: 2.5px; color: rgba(255,255,255,.55); text-transform: uppercase;
      padding: 6px 16px; border: 1px solid rgba(255,255,255,.2); border-radius: 30px; backdrop-filter: blur(4px); }

    .cover-body { position: relative; z-index: 1; flex: 1; display: flex; flex-direction: column; justify-content: center; padding: 0 56px; }
    .cover-eyebrow { display: flex; align-items: center; gap: 10px; margin-bottom: 20px; }
    .cover-eyebrow-line { height: 1px; width: 32px; background: rgba(255,255,255,.35); }
    .cover-eyebrow-text { font-size: 10px; font-weight: 700; letter-spacing: 2.5px; color: rgba(255,255,255,.45); text-transform: uppercase; }
    .cover-title { font-family: 'Plus Jakarta Sans', 'Inter', sans-serif; font-size: 46px; font-weight: 800;
      line-height: 1.08; letter-spacing: -1px; margin-bottom: 18px; color: white; text-wrap: balance; }
    .cover-sub { font-size: 14.5px; color: rgba(255,255,255,.6); max-width: 500px; line-height: 1.75; }

    .cover-divider { position: relative; z-index: 1; height: 1px; background: rgba(255,255,255,.1); margin: 44px 56px 0; }

    .cover-stats { position: relative; z-index: 1; display: grid; grid-template-columns: repeat(4,1fr); }
    .cover-stat { padding: 26px 28px; border-right: 1px solid rgba(255,255,255,.1); }
    .cover-stat:last-child { border-right: none; }
    .cover-stat-v { font-family: 'Plus Jakarta Sans', 'Inter', sans-serif; font-size: 34px; font-weight: 800; line-height: 1; margin-bottom: 6px; letter-spacing: -1px; }
    .cover-stat-l { font-size: 9.5px; color: rgba(255,255,255,.45); text-transform: uppercase; letter-spacing: 1.2px; font-weight: 600; }

    .cover-bottom { position: relative; z-index: 1; padding: 20px 56px; display: flex; justify-content: space-between; align-items: center;
      border-top: 1px solid rgba(255,255,255,.08); font-size: 10.5px; color: rgba(255,255,255,.35); }
    .cover-badge { display: flex; align-items: center; gap: 7px; padding: 5px 14px; border: 1px solid rgba(255,255,255,.15); border-radius: 20px; font-size: 10px; font-weight: 600; color: rgba(255,255,255,.5); }

    /* ── Body layout ── */
    .body { max-width: 840px; margin: 0 auto; padding: 52px 56px 68px; }
    @media print { .body { padding: 38px 48px 52px; } }

    /* ── Running header ── */
    .doc-header { display: flex; justify-content: space-between; align-items: center; padding-bottom: 18px;
      border-bottom: 1px solid #E8EDF5; margin-bottom: 40px; }
    .doc-header-left { font-size: 11px; color: #9CA3AF; line-height: 1.6; }
    .doc-header-left strong { color: #4B5563; font-weight: 700; }
    .doc-header-right { font-size: 11px; color: #9CA3AF; text-align: right; }
    .doc-header-accent { display: inline-block; width: 28px; height: 2px; background: linear-gradient(to right, ${P}, ${A}); border-radius: 2px; vertical-align: middle; margin-right: 8px; }

    /* ── Section headings ── */
    .section { margin-bottom: 44px; page-break-inside: avoid; }
    .section-header { display: flex; align-items: baseline; gap: 14px; margin-bottom: 18px; }
    .section-num { font-size: 9px; font-weight: 800; color: ${P}; letter-spacing: 2.5px; text-transform: uppercase;
      background: ${P}12; padding: 3px 9px; border-radius: 4px; white-space: nowrap; }
    h2 { font-family: 'Plus Jakarta Sans', 'Inter', sans-serif; font-size: 20px; font-weight: 800;
      color: #0A1230; letter-spacing: -.4px; line-height: 1.25; }
    h3 { font-family: 'Plus Jakarta Sans', 'Inter', sans-serif; font-size: 14.5px; font-weight: 700; color: #0A1230; margin-bottom: 10px; }
    p { font-size: 13.5px; color: #374151; line-height: 1.8; margin-bottom: 13px; }
    p:last-child { margin-bottom: 0; }

    /* ── KPI row ── */
    .kpi-row { display: grid; grid-template-columns: repeat(4,1fr); gap: 14px; margin: 28px 0; }
    .kpi { border-radius: 16px; padding: 22px 18px; text-align: center; position: relative; overflow: hidden;
      background: linear-gradient(145deg, #F8FAFF 0%, #F0F4FF 100%); border: 1px solid #E4EBF8; }
    .kpi::before { content: ''; position: absolute; top: -20px; right: -20px; width: 80px; height: 80px; border-radius: 50%; background: ${P}06; }
    .kpi-v { font-family: 'Plus Jakarta Sans', 'Inter', sans-serif; font-size: 34px; font-weight: 800;
      line-height: 1; margin-bottom: 7px; letter-spacing: -1px; }
    .kpi-l { font-size: 9.5px; font-weight: 700; color: #9CA3AF; text-transform: uppercase; letter-spacing: 1px; }

    /* ── Chart row ── */
    .chart-row { display: flex; align-items: center; gap: 36px; margin: 24px 0; }
    .chart-legend { display: flex; flex-direction: column; gap: 12px; }
    .legend-item { display: flex; align-items: center; gap: 10px; }
    .legend-dot { width: 10px; height: 10px; border-radius: 50%; flex-shrink: 0; }
    .legend-label { font-size: 12.5px; color: #6B7280; }
    .legend-val { font-size: 14px; font-weight: 700; color: #0A1230; margin-left: 4px; font-variant-numeric: tabular-nums; }
    .legend-pct { font-size: 11px; color: #9CA3AF; font-weight: 400; margin-left: 3px; }

    /* ── AI insight card ── */
    .ai-card { background: linear-gradient(135deg, #EFF6FF 0%, #F5F3FF 100%); border: 1px solid #C7D2FE;
      border-radius: 16px; padding: 24px 26px; margin-bottom: 28px; position: relative; overflow: hidden; }
    .ai-card::before { content: ''; position: absolute; top: -30px; right: -30px; width: 140px; height: 140px;
      border-radius: 50%; background: rgba(99,102,241,.05); }
    .ai-card-label { font-size: 9.5px; font-weight: 800; color: ${P}; text-transform: uppercase; letter-spacing: 2px;
      margin-bottom: 12px; display: flex; align-items: center; gap: 8px; position: relative; }
    .ai-orb { width: 20px; height: 20px; border-radius: 50%; background: linear-gradient(135deg, ${P}, ${A});
      display: inline-flex; align-items: center; justify-content: center; font-size: 9px; color: white; flex-shrink: 0; }
    .ai-card-text { font-size: 13.5px; color: #1E3A8A; line-height: 1.85; position: relative; }
    .theme-row { display: flex; flex-wrap: wrap; gap: 7px; margin-top: 16px; }
    .theme-pill { background: white; border: 1px solid #BFDBFE; border-radius: 30px; padding: 5px 14px;
      font-size: 11.5px; color: #1D4ED8; font-weight: 500; box-shadow: 0 1px 3px rgba(37,99,235,.06); }

    /* ── Quote ── */
    .quote-card { border-left: 3px solid ${P}; background: #F8FAFF; border-radius: 0 12px 12px 0;
      padding: 16px 20px; margin-bottom: 12px; }
    .quote-text { font-size: 13.5px; color: #374151; font-style: italic; line-height: 1.8; }

    /* ── IFI block ── */
    .ifi-card { display: flex; align-items: center; gap: 32px; background: #F8FAFF; border: 1px solid #E8EDF5;
      border-radius: 16px; padding: 24px 28px; }
    .ifi-desc { font-size: 13px; color: #6B7280; line-height: 1.75; max-width: 400px; }

    /* ── Engine bars ── */
    .engine-row { display: flex; align-items: center; gap: 16px; margin-bottom: 14px; }
    .engine-name { font-size: 12.5px; color: #374151; font-weight: 500; width: 170px; flex-shrink: 0; }
    .engine-bar { flex: 1; }
    .engine-pct { font-size: 12.5px; font-weight: 700; width: 40px; text-align: right; flex-shrink: 0; font-variant-numeric: tabular-nums; }

    /* ── Enumerator table ── */
    table { width: 100%; border-collapse: collapse; font-size: 12.5px; }
    thead tr { background: linear-gradient(to right, ${P}0A, ${A}08); }
    th { padding: 11px 15px; text-align: left; font-size: 9.5px; font-weight: 700; color: #6B7280;
      text-transform: uppercase; letter-spacing: .8px; border-bottom: 2px solid ${P}20; white-space: nowrap; }
    td { padding: 12px 15px; border-bottom: 1px solid #F4F6FA; vertical-align: middle; }
    tr:nth-child(even) td { background: #FAFBFF; }
    tr:last-child td { border-bottom: none; }
    .chip { display: inline-flex; align-items: center; justify-content: center; min-width: 32px; padding: 3px 9px;
      border-radius: 6px; font-size: 11px; font-weight: 700; font-variant-numeric: tabular-nums; }
    .chip-pass   { background: #DCFCE7; color: #166534; }
    .chip-flag   { background: #FEF9C3; color: #854D0E; }
    .chip-reject { background: #FEE2E2; color: #991B1B; }

    /* ── Tier badge ── */
    .tier { display: inline-block; padding: 4px 12px; border-radius: 30px; font-size: 10.5px; font-weight: 700; }
    .tier-ex    { background: #DCFCE7; color: #166534; }
    .tier-good  { background: #DBEAFE; color: #1E40AF; }
    .tier-coach { background: #FEF9C3; color: #854D0E; }
    .tier-risk  { background: #FEE2E2; color: #991B1B; }

    /* ── Verify list ── */
    .verify-item { display: flex; align-items: flex-start; gap: 14px; padding: 12px 0; border-bottom: 1px solid #F4F6FA; }
    .verify-item:last-child { border-bottom: none; }
    .verify-icon { width: 26px; height: 26px; border-radius: 50%; display: flex; align-items: center; justify-content: center;
      flex-shrink: 0; font-size: 12px; margin-top: 1px; }
    .verify-icon-pass { background: #DCFCE7; color: #166534; }
    .verify-detail { font-size: 13px; color: #374151; line-height: 1.65; }
    .verify-detail strong { color: #0A1230; }

    /* ── Recommendation cards ── */
    .rec-card { border-radius: 14px; padding: 20px 22px; margin-bottom: 14px; display: flex; gap: 18px; align-items: flex-start;
      border-left: 4px solid transparent; }
    .rec-num { width: 32px; height: 32px; border-radius: 50%; display: flex; align-items: center; justify-content: center;
      font-size: 13px; font-weight: 800; flex-shrink: 0; }
    .rec-body h4 { font-family: 'Plus Jakarta Sans', 'Inter', sans-serif; font-size: 14px; font-weight: 700;
      color: #0A1230; margin-bottom: 5px; }
    .rec-body p { font-size: 13px; color: #6B7280; margin: 0; line-height: 1.7; }

    /* ── Quality banner ── */
    .quality-banner { border-radius: 14px; padding: 18px 22px; margin-bottom: 32px; display: flex; align-items: flex-start; gap: 16px; }
    .quality-icon { font-size: 22px; flex-shrink: 0; margin-top: 1px; }
    .quality-text strong { display: block; font-family: 'Plus Jakarta Sans', 'Inter', sans-serif; font-size: 14.5px; font-weight: 700; margin-bottom: 4px; }
    .quality-text span { font-size: 13px; }

    /* ── Section full-bleed accent ── */
    .section-accent { margin: 0 -56px; padding: 24px 56px 28px; margin-bottom: 36px;
      background: linear-gradient(to right, ${P}08, ${A}06); border-top: 1px solid ${P}15; border-bottom: 1px solid ${P}10; }

    /* ── Footer ── */
    .doc-footer { margin-top: 52px; padding-top: 22px; display: flex; justify-content: space-between; align-items: center;
      border-top: 1px solid #E8EDF5; }
    .doc-footer-left { font-size: 11px; color: #9CA3AF; line-height: 1.75; }
    .doc-footer-left strong { color: #6B7280; font-weight: 600; }
    .cert { display: inline-flex; align-items: center; gap: 8px; padding: 8px 18px; border-radius: 10px; font-size: 11.5px; font-weight: 700; }

    /* ── Print utilities ── */
    .pb { page-break-before: always; }
    .no-break { page-break-inside: avoid; }
    .print-bar { position: fixed; top: 0; left: 0; right: 0; z-index: 200; background: #0A1230;
      padding: 10px 32px; display: flex; align-items: center; justify-content: space-between;
      box-shadow: 0 2px 12px rgba(0,0,0,.3); }
    .print-bar-left { display: flex; align-items: center; gap: 12px; }
    .print-bar-dot { width: 8px; height: 8px; border-radius: 50%; background: ${P}; }
    .print-bar-title { font-size: 12px; font-weight: 600; color: rgba(255,255,255,.6); }
    .print-bar-project { font-size: 12px; font-weight: 700; color: rgba(255,255,255,.9); }
    .print-btn { background: linear-gradient(135deg, ${P}, ${A}); color: white; border: none;
      border-radius: 8px; padding: 8px 24px; font-size: 13px; font-weight: 600; cursor: pointer;
      font-family: inherit; box-shadow: 0 2px 8px ${P}40; transition: opacity .15s; }
    .print-btn:hover { opacity: .9; }
    @media print { .print-bar { display: none !important; } body { padding-top: 0; } }
    body { padding-top: 48px; }
    @media print { body { padding-top: 0; } }
  `;

  // ── Shared building blocks ───────────────────────────────────────────────────

  const logoHtml = ctx.logoDataUrl
    ? `<div class="cover-logo"><img src="${ctx.logoDataUrl}" alt="${ctx.orgName}"></div>`
    : `<div class="cover-logo"><div class="cover-logo-text">FIELDSC◉RE</div><div class="cover-logo-tag">ResearchOS · Verify · Analyze · Decide</div></div>`;

  const runningHeader = `
    <div class="doc-header">
      <div class="doc-header-left"><span class="doc-header-accent"></span><strong>${ctx.orgName}</strong> · ${title}</div>
      <div class="doc-header-right">${ctx.projectName} · ${date}</div>
    </div>`;

  const kpiRow = `
    <div class="kpi-row">
      <div class="kpi"><div class="kpi-v">${ctx.submissionCount.toLocaleString()}</div><div class="kpi-l">Submissions</div></div>
      <div class="kpi"><div class="kpi-v" style="color:#059669">${passP}%</div><div class="kpi-l">Pass Rate</div></div>
      <div class="kpi"><div class="kpi-v" style="color:#D97706">${flagP}%</div><div class="kpi-l">Flagged</div></div>
      <div class="kpi"><div class="kpi-v" style="color:#DC2626">${rejP}%</div><div class="kpi-l">Rejected</div></div>
    </div>`;

  const verdictChart = `
    <div class="chart-row">
      ${donut(passP, flagP, rejP)}
      <div class="chart-legend">
        <div class="legend-item"><div class="legend-dot" style="background:#059669"></div><span class="legend-label">Pass</span><span class="legend-val">${ctx.passCount.toLocaleString()} <span style="color:#9CA3AF;font-weight:400;font-size:11px">(${passP}%)</span></span></div>
        <div class="legend-item"><div class="legend-dot" style="background:#D97706"></div><span class="legend-label">Flagged</span><span class="legend-val">${ctx.flagCount.toLocaleString()} <span style="color:#9CA3AF;font-weight:400;font-size:11px">(${flagP}%)</span></span></div>
        <div class="legend-item"><div class="legend-dot" style="background:#DC2626"></div><span class="legend-label">Rejected</span><span class="legend-val">${ctx.rejectCount.toLocaleString()} <span style="color:#9CA3AF;font-weight:400;font-size:11px">(${rejP}%)</span></span></div>
        ${ctx.ifScore !== undefined ? `<div class="legend-item" style="margin-top:8px;padding-top:8px;border-top:1px solid #F1F5F9"><div class="legend-dot" style="background:${P}"></div><span class="legend-label">IFI Score</span><span class="legend-val">${ctx.ifScore}/100</span></div>` : ''}
      </div>
    </div>`;

  const aiCard = () => {
    if (!ctx.aiSummary && !ctx.aiThemes?.length) return '';
    return `<div class="ai-card">
      <div class="ai-card-label">◉ Ada AI Analysis</div>
      ${ctx.aiSummary ? `<div class="ai-card-text">${ctx.aiSummary}</div>` : ''}
      ${ctx.aiThemes?.length ? `<div class="theme-row">${ctx.aiThemes.map(t => `<span class="theme-pill">${t}</span>`).join('')}</div>` : ''}
    </div>`;
  };

  const quotesBlock = () => {
    if (!ctx.aiQuotes?.length) return '';
    return `<div class="section">
      <div class="section-num">Voice of Respondent</div>
      <h2>What People Said</h2>
      ${ctx.aiQuotes.slice(0, 3).map(q => `<div class="quote-card"><div class="quote-text">"${q}"</div></div>`).join('')}
    </div>`;
  };

  const ifiSection = () => {
    if (ctx.ifScore === undefined) return '';
    const desc = ctx.ifScore >= 75
      ? 'The responses closely match the research intent. Thematic consistency is high and respondent engagement is genuine.'
      : ctx.ifScore >= 55
      ? 'Moderate alignment with research intent. Some responses show inconsistency — review flagged items before drawing conclusions.'
      : 'Low alignment detected. A re-collection exercise or deeper qualitative review is recommended before analysis.';
    return `<div class="section">
      <div class="section-num">05 · Signal Quality</div>
      <h2>Intent Fidelity Index</h2>
      <div class="ifi-card">
        ${ifiGauge(ctx.ifScore)}
        <div class="ifi-desc">${desc}</div>
      </div>
    </div>`;
  };

  const engineSection = () => {
    if (!ctx.engineRows?.length) return '';
    const rows = ctx.engineRows.map(e => {
      const t = e.total || 1;
      const p = pct(e.pass, t);
      const f = pct(e.flag, t);
      const r = pct(e.reject, t);
      const color = p >= 80 ? '#059669' : p >= 60 ? '#D97706' : '#DC2626';
      return `<div class="engine-row no-break">
        <div class="engine-name">${e.name}</div>
        <div class="engine-bar">${stackedBar(p, f, r, 10)}</div>
        <div class="engine-pct" style="color:${color}">${p}%</div>
      </div>`;
    }).join('');
    return `<div class="section">
      <div class="section-num">03 · Verification Engines</div>
      <h2>Engine Breakdown</h2>
      <p>Each verification engine runs independently. A submission's final verdict is a weighted composite of all active engine scores.</p>
      <div style="margin-top:20px">
        <div style="display:flex;gap:20px;font-size:10.5px;color:#9CA3AF;margin-bottom:12px">
          <span>■ <span style="color:#059669">Pass</span></span>
          <span>■ <span style="color:#D97706">Flag</span></span>
          <span>■ <span style="color:#DC2626">Reject</span></span>
        </div>
        ${rows}
      </div>
    </div>`;
  };

  const enumSection = (sectionNum = '04') => {
    if (!ctx.enumeratorRows?.length) return '';
    const sorted = [...ctx.enumeratorRows].sort((a, b) => pct(b.pass, b.submissions || 1) - pct(a.pass, a.submissions || 1));
    const rows = sorted.map(e => {
      const t = e.submissions || 1;
      const p = pct(e.pass, t);
      const [tierClass, tierLabel] = p >= 85 ? ['tier-ex','Excellent'] : p >= 70 ? ['tier-good','Good'] : p >= 55 ? ['tier-coach','Needs Coaching'] : ['tier-risk','At Risk'];
      return `<tr>
        <td style="font-weight:600;color:#0A1230">${e.name}</td>
        <td style="text-align:center">${e.submissions}</td>
        <td style="text-align:center"><span class="chip chip-pass">${e.pass}</span></td>
        <td style="text-align:center"><span class="chip chip-flag">${e.flag}</span></td>
        <td style="text-align:center"><span class="chip chip-reject">${e.reject}</span></td>
        <td><div style="display:flex;align-items:center;gap:8px">${stackedBar(pct(e.pass,t), pct(e.flag,t), pct(e.reject,t), 7)}<span style="font-size:11.5px;font-weight:700;color:#0A1230">${p}%</span></div></td>
        <td><span class="tier ${tierClass}">${tierLabel}</span></td>
      </tr>`;
    }).join('');
    return `<div class="section">
      <div class="section-num">${sectionNum} · Field Team</div>
      <h2>Enumerator Performance</h2>
      <p>Ranked by pass rate. Sorted highest to lowest. Tier thresholds: Excellent ≥85%, Good ≥70%, Needs Coaching ≥55%, At Risk &lt;55%.</p>
      <table style="margin-top:18px">
        <thead><tr><th>Enumerator</th><th style="text-align:center">Total</th><th style="text-align:center">Pass</th><th style="text-align:center">Flag</th><th style="text-align:center">Reject</th><th>Pass Rate</th><th>Tier</th></tr></thead>
        <tbody>${rows}</tbody>
      </table>
    </div>`;
  };

  const verifySection = (sectionNum = '05') => `
    <div class="section">
      <div class="section-num">${sectionNum} · Methodology</div>
      <h2>Verification Statement</h2>
      <p>Every submission in this dataset was processed by FieldScore's multi-engine verification pipeline. No submission was excluded from screening.</p>
      ${[
        ['GPS', 'Coordinates validated against approved survey boundaries. Accuracy, altitude, and movement plausibility checked in real time.'],
        ['Duration', 'Interview length validated against the expected range for this questionnaire.'],
        ['Audio', 'Recordings screened for genuine two-voice conversation. Silent recordings and single-voice reads were flagged.'],
        ['Image', 'Photographs fingerprinted and compared across all submissions. Duplicates, downloaded images, and AI-generated photos were detected.'],
        ['Duplicates', 'Submission fingerprinting applied across all interviews. Near-identical responses from the same device or location were identified.'],
        ['AI Detection', 'Text and image content screened for AI-generated responses.'],
      ].map(([label, desc]) => `<div class="verify-item">
        <div class="verify-icon verify-icon-pass">✓</div>
        <div class="verify-detail"><strong>${label}</strong> — ${desc}</div>
      </div>`).join('')}
    </div>`;

  const recommendations = () => {
    const recs: Array<{ title: string; body: string; color: string; bg: string }> = [];
    if (rejP > 10) recs.push({ title: 'Re-collect rejected submissions', body: `${ctx.rejectCount.toLocaleString()} submissions (${rejP}%) were rejected. Identify the enumerators and LGAs contributing the most rejections and schedule targeted re-interviews.`, color: '#991B1B', bg: '#FEF2F2' });
    if (flagP > 15) recs.push({ title: 'Resolve open flags before analysis', body: `${ctx.flagCount.toLocaleString()} submissions (${flagP}%) are flagged for review. Senior supervisors should clear these before the dataset is passed to analysis.`, color: '#854D0E', bg: '#FFFBEB' });
    if (ctx.enumeratorRows?.some(e => pct(e.pass, e.submissions || 1) < 55)) recs.push({ title: 'Retrain or remove at-risk enumerators', body: 'One or more enumerators have a pass rate below 55%. This indicates systematic issues — whether technique, fraud, or connectivity — that warrant immediate investigation.', color: '#1E40AF', bg: '#EFF6FF' });
    if (passP >= 85) recs.push({ title: 'Dataset cleared for analysis', body: `With a ${passP}% pass rate, this dataset meets high-quality thresholds. Proceed to analysis and reporting with confidence.`, color: '#166534', bg: '#F0FDF4' });
    if (!recs.length) return '';
    return `<div class="section">
      <div class="section-num">0${recs.length > 0 ? '6' : '5'} · Next Steps</div>
      <h2>Recommendations</h2>
      ${recs.map((r, i) => `<div class="rec-card" style="background:${r.bg}">
        <div class="rec-num" style="background:${r.color}22;color:${r.color}">0${i + 1}</div>
        <div class="rec-body"><h4 style="color:${r.color}">${r.title}</h4><p>${r.body}</p></div>
      </div>`).join('')}
    </div>`;
  };

  const qualityBanner = () => {
    if (passP >= 85) return `<div class="quality-banner" style="background:#F0FDF4;border:1px solid #BBF7D0">
      <div class="quality-icon">✅</div>
      <div class="quality-text"><strong style="color:#166534">Dataset meets quality standards</strong><span style="color:#166534">${passP}% pass rate across ${ctx.submissionCount.toLocaleString()} submissions. Cleared for analysis and client delivery.</span></div>
    </div>`;
    if (rejP > 15) return `<div class="quality-banner" style="background:#FEF2F2;border:1px solid #FECACA">
      <div class="quality-icon">⚠️</div>
      <div class="quality-text"><strong style="color:#991B1B">High rejection rate — review before delivery</strong><span style="color:#991B1B">${rejP}% of submissions did not pass verification. A re-collection exercise is recommended for the worst-performing areas.</span></div>
    </div>`;
    return `<div class="quality-banner" style="background:#FFFBEB;border:1px solid #FDE68A">
      <div class="quality-icon">🔶</div>
      <div class="quality-text"><strong style="color:#854D0E">Flags require resolution before analysis</strong><span style="color:#854D0E">${flagP}% of submissions are awaiting supervisor review. Resolve these before sharing the dataset.</span></div>
    </div>`;
  };

  const docFooter = `
    <div class="doc-footer">
      <div class="doc-footer-left">
        Verified by <strong>${ctx.generatedBy}</strong> · ${ctx.orgName}<br>
        ${footerLine}
      </div>
      <div class="cert" style="background:${P}18;border:1px solid ${P}44;color:${P}">
        ◉ FieldScore Verified · ${ctx.passCount.toLocaleString()}/${ctx.submissionCount.toLocaleString()} passed
      </div>
    </div>`;

  // ── Cover page ───────────────────────────────────────────────────────────────

  const cover = `
    <div class="cover">
      <div class="cover-top">
        ${logoHtml}
        <div class="cover-type">${title}</div>
      </div>
      <div class="cover-body">
        <div class="cover-eyebrow">
          <div class="cover-eyebrow-line"></div>
          <div class="cover-eyebrow-text">Field Research Quality Report</div>
        </div>
        <div class="cover-title">${ctx.projectName}</div>
        <div class="cover-sub">${ctx.orgName} · Verified by FieldScore Intelligence Engine · ${date}</div>
      </div>
      <div class="cover-divider"></div>
      <div class="cover-stats">
        <div class="cover-stat"><div class="cover-stat-v">${ctx.submissionCount.toLocaleString()}</div><div class="cover-stat-l">Submissions Screened</div></div>
        <div class="cover-stat"><div class="cover-stat-v" style="color:#6EE7B7">${passP}%</div><div class="cover-stat-l">Pass Rate</div></div>
        <div class="cover-stat"><div class="cover-stat-v" style="color:#FCD34D">${flagP}%</div><div class="cover-stat-l">Flagged for Review</div></div>
        <div class="cover-stat"><div class="cover-stat-v" style="color:#FCA5A5">${rejP}%</div><div class="cover-stat-l">Rejected</div></div>
      </div>
      <div class="cover-bottom">
        <span>${ctx.generatedBy} · ${footerLine}</span>
        <div class="cover-badge">◉ FieldScore Verified</div>
      </div>
    </div>`;

  // ── Per-report bodies ────────────────────────────────────────────────────────

  let body = '';

  if (reportId === 'executive' || reportId === 'client') {
    body = `
      ${cover}
      <div class="body">
        ${runningHeader}
        ${qualityBanner()}
        <div class="section">
          <div class="section-num">01 · Overview</div>
          <h2>Dataset Summary</h2>
          ${kpiRow}
          ${verdictChart}
        </div>
        ${ctx.aiSummary || ctx.aiThemes?.length ? `<div class="section"><div class="section-num">02 · Intelligence</div><h2>Ada's Analysis</h2>${aiCard()}</div>` : ''}
        ${quotesBlock()}
        ${ifiSection()}
        <div class="section">
          <div class="section-num">0${ctx.ifScore !== undefined ? '6' : '5'} · Key Findings</div>
          <h2>Summary of Findings</h2>
          <p>This dataset was verified by FieldScore's multi-engine pipeline across <strong>${ctx.submissionCount.toLocaleString()} submissions</strong>${ctx.enumeratorRows?.length ? ` collected by <strong>${ctx.enumeratorRows.length} field enumerators</strong>` : ''}.</p>
          <p><strong>${ctx.passCount.toLocaleString()} submissions (${passP}%)</strong> cleared all verification checks and are included in the clean dataset.
          ${ctx.flagCount > 0 ? ` <strong>${ctx.flagCount.toLocaleString()} (${flagP}%)</strong> were flagged for supervisor review.` : ''}
          ${ctx.rejectCount > 0 ? ` <strong>${ctx.rejectCount.toLocaleString()} (${rejP}%)</strong> failed one or more hard checks and have been excluded.` : ' No submissions were rejected.'}</p>
        </div>
        ${recommendations()}
        ${enumSection('07')}
        ${verifySection('08')}
        ${docFooter}
      </div>`;

  } else if (reportId === 'technical') {
    body = `
      ${cover}
      <div class="body">
        ${runningHeader}
        <div class="section">
          <div class="section-num">01 · Summary</div>
          <h2>Quality Overview</h2>
          ${kpiRow}
          ${verdictChart}
        </div>
        ${engineSection()}
        ${enumSection('04')}
        ${ifiSection()}
        ${verifySection('06')}
        ${recommendations()}
        ${docFooter}
      </div>`;

  } else if (reportId === 'enumerator') {
    const top = ctx.enumeratorRows?.slice().sort((a,b) => pct(b.pass, b.submissions||1) - pct(a.pass,a.submissions||1)).slice(0,3) || [];
    const bottom = ctx.enumeratorRows?.slice().sort((a,b) => pct(a.pass,a.submissions||1) - pct(b.pass,b.submissions||1)).slice(0,3) || [];
    const spotlightHtml = (top.length || bottom.length) ? `<div class="section">
      <div class="section-num">02 · Spotlight</div>
      <h2>Top &amp; Bottom Performers</h2>
      <div style="display:grid;grid-template-columns:1fr 1fr;gap:20px;margin-top:16px">
        ${top.length ? `<div>
          <div style="font-size:10px;font-weight:700;color:#059669;letter-spacing:1px;text-transform:uppercase;margin-bottom:10px">Top Performers</div>
          ${top.map(e => `<div style="display:flex;align-items:center;justify-content:space-between;padding:8px 0;border-bottom:1px solid #F4F6FA">
            <span style="font-size:13px;font-weight:600;color:#0A1230">${e.name}</span>
            <span style="font-size:13px;font-weight:800;color:#059669">${pct(e.pass, e.submissions||1)}%</span>
          </div>`).join('')}
        </div>` : ''}
        ${bottom.length ? `<div>
          <div style="font-size:10px;font-weight:700;color:#DC2626;letter-spacing:1px;text-transform:uppercase;margin-bottom:10px">Needs Attention</div>
          ${bottom.map(e => `<div style="display:flex;align-items:center;justify-content:space-between;padding:8px 0;border-bottom:1px solid #F4F6FA">
            <span style="font-size:13px;font-weight:600;color:#0A1230">${e.name}</span>
            <span style="font-size:13px;font-weight:800;color:#DC2626">${pct(e.pass, e.submissions||1)}%</span>
          </div>`).join('')}
        </div>` : ''}
      </div>
    </div>` : '';
    body = `
      ${cover}
      <div class="body">
        ${runningHeader}
        <div class="section">
          <div class="section-num">01 · Team Overview</div>
          <h2>Field Team Summary</h2>
          ${kpiRow}
        </div>
        ${spotlightHtml}
        ${enumSection('03')}
        ${recommendations()}
        ${aiCard() ? `<div class="section"><div class="section-num">05 · Intelligence</div><h2>Ada's Notes</h2>${aiCard()}</div>` : ''}
        ${docFooter}
      </div>`;
  }

  return `<!DOCTYPE html>
<html lang="en"><head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>${title} — ${ctx.projectName}</title>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@600;700;800&family=Inter:wght@400;500;600;700;800&display=swap">
<style>${css}</style>
</head><body>
<div class="print-bar">
  <div class="print-bar-left">
    <div class="print-bar-dot"></div>
    <span class="print-bar-title">${ctx.orgName} ·</span>
    <span class="print-bar-project">${ctx.projectName}</span>
  </div>
  <button class="print-btn" onclick="window.print()">⬇ Save as PDF</button>
</div>
${body}
</body></html>`;
}
