// Local report generator — produces a real downloadable HTML file when the
// backend API is unavailable. Print → Save as PDF works in every browser.
// For .xlsx we produce a proper CSV Blob.

export interface EnumeratorRow {
  name: string;
  submissions: number;
  pass: number;
  flag: number;
  reject: number;
}

export interface EngineRow {
  name: string;
  pass: number;
  flag: number;
  reject: number;
  total: number;
}

export interface ReportContext {
  projectName: string;
  orgName: string;
  submissionCount: number;
  passCount: number;
  flagCount: number;
  rejectCount: number;
  generatedBy: string;
  // AI insights from InsightScore
  aiSummary?: string;
  aiThemes?: string[];
  aiQuotes?: string[];
  ifScore?: number;
  // Real per-enumerator data
  enumeratorRows?: EnumeratorRow[];
  // Real per-engine data
  engineRows?: EngineRow[];
  // Org branding
  primaryColor?: string;
  accentColor?: string;
  brandFont?: string;
  brandFooter?: string;
  logoDataUrl?: string;
}

export function generateLocalReport(
  reportId: string,
  format: 'docx' | 'pptx' | 'xlsx',
  ctx: ReportContext
): { blob: Blob; filename: string } | null {
  const d = new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' });
  if (format === 'xlsx') return generateCsv(reportId, ctx, d);
  const html = generateHtml(reportId, ctx, d);
  const blob = new Blob([html], { type: 'text/html' });
  return { blob, filename: `${slug(ctx.projectName)}-${reportId}-report.html` };
}

function slug(s: string) {
  return s.replace(/\s+/g, '-').replace(/[^a-zA-Z0-9-]/g, '').toLowerCase();
}

function pct(n: number, total: number) {
  return total > 0 ? Math.round((n / total) * 100) : 0;
}

// ── CSV / Excel ───────────────────────────────────────────────────────────────

function generateCsv(reportId: string, ctx: ReportContext, date: string): { blob: Blob; filename: string } {
  const total = ctx.submissionCount || 1;
  const pass = pct(ctx.passCount, total);
  const flag = pct(ctx.flagCount, total);
  const rej = pct(ctx.rejectCount, total);

  let rows: string[][] = [];

  if (reportId === 'technical') {
    rows = [['Engine Check', 'Pass', 'Flag', 'Reject', 'Total']];
    if (ctx.engineRows?.length) {
      ctx.engineRows.forEach(e => rows.push([e.name, String(e.pass), String(e.flag), String(e.reject), String(e.total)]));
    } else {
      [['GPS Accuracy', pass, flag, rej], ['Audio Quality', pass, flag, rej], ['Image Clarity', pass, flag, rej],
       ['Duration', pass, flag, rej], ['Duplicate Check', pass, 0, rej]].forEach(([n, p, f, r]) =>
        rows.push([String(n), String(p) + '%', String(f) + '%', String(r) + '%', String(total)]));
    }
  } else if (reportId === 'enumerator') {
    rows = [['Enumerator', 'Submissions', 'Pass', 'Flag', 'Reject', 'Pass Rate']];
    if (ctx.enumeratorRows?.length) {
      ctx.enumeratorRows.forEach(e => {
        const t = e.submissions || 1;
        rows.push([e.name, String(e.submissions), String(e.pass), String(e.flag), String(e.reject), pct(e.pass, t) + '%']);
      });
    } else {
      rows.push([ctx.generatedBy, String(ctx.submissionCount), String(ctx.passCount), String(ctx.flagCount), String(ctx.rejectCount), pass + '%']);
    }
  } else {
    rows = [
      ['Metric', 'Value'],
      ['Project', ctx.projectName],
      ['Organisation', ctx.orgName],
      ['Generated', date],
      ['Total Submissions', String(ctx.submissionCount)],
      ['Pass', String(ctx.passCount) + ' (' + pass + '%)'],
      ['Flagged', String(ctx.flagCount) + ' (' + flag + '%)'],
      ['Rejected', String(ctx.rejectCount) + ' (' + rej + '%)'],
      ['Generated By', ctx.generatedBy],
    ];
    if (ctx.ifScore !== undefined) rows.push(['Intent Fidelity Index', String(ctx.ifScore) + '/100']);
  }

  const csv = rows.map(r => r.map(c => `"${String(c).replace(/"/g, '""')}"`).join(',')).join('\n');
  return { blob: new Blob([csv], { type: 'text/csv' }), filename: `${slug(ctx.projectName)}-${reportId}.csv` };
}

// ── HTML report ───────────────────────────────────────────────────────────────

function generateHtml(reportId: string, ctx: ReportContext, date: string): string {
  const total = ctx.submissionCount || 1;
  const passN = ctx.passCount;
  const flagN = ctx.flagCount;
  const rejectN = ctx.rejectCount;
  const passP = pct(passN, total);
  const flagP = pct(flagN, total);
  const rejectP = pct(rejectN, total);
  const accent = ctx.primaryColor || '#2463EB';
  const accent2 = ctx.accentColor || '#7C3AED';
  const fontStack = ctx.brandFont
    ? `'${ctx.brandFont}', Inter, 'Helvetica Neue', Arial, sans-serif`
    : "Inter, 'Helvetica Neue', Arial, sans-serif";
  const footerText = ctx.brandFooter || 'Confidential · ResearchOS · FieldScore';

  const titles: Record<string, string> = {
    executive: 'Executive Summary',
    client: 'Client Delivery Report',
    enumerator: 'Enumerator Performance Report',
    technical: 'Technical Quality Report',
  };
  const title = titles[reportId] || 'Field Research Report';

  const css = `
    @page { size: A4; margin: 18mm 20mm; }
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: ${fontStack}; background: white; color: #111827; font-size: 13px; line-height: 1.65; }
    .wrap { max-width: 860px; margin: 0 auto; padding: 36px 40px; }
    /* Header */
    .page-header { display: flex; align-items: flex-start; justify-content: space-between; padding-bottom: 22px; border-bottom: 3px solid; border-image: linear-gradient(to right, ${accent}, ${accent2}) 1; margin-bottom: 32px; }
    .brand-name { font-size: 12px; font-weight: 800; letter-spacing: 3px; color: #0A1230; }
    .brand-name em { color: ${accent}; font-style: normal; }
    .brand-tag { font-size: 10px; color: #9CA3AF; letter-spacing: 1px; margin-top: 3px; }
    .header-meta { text-align: right; font-size: 11px; color: #6B7280; line-height: 1.7; }
    .header-meta strong { color: #0A1230; font-size: 13px; display: block; margin-bottom: 2px; }
    /* Title block */
    .title-block { margin-bottom: 32px; }
    .report-label { font-size: 10.5px; font-weight: 700; color: ${accent}; text-transform: uppercase; letter-spacing: 1.2px; margin-bottom: 8px; }
    h1 { font-size: 28px; font-weight: 800; color: #0A1230; letter-spacing: -.5px; line-height: 1.2; margin-bottom: 8px; }
    .subtitle { font-size: 13.5px; color: #6B7280; }
    /* Stat grid */
    .stats { display: grid; grid-template-columns: repeat(4, 1fr); gap: 12px; margin: 28px 0; }
    .stat { border: 1px solid #E8EDF5; border-radius: 12px; padding: 16px 14px; text-align: center; }
    .stat-value { font-size: 28px; font-weight: 800; line-height: 1; margin-bottom: 5px; }
    .stat-label { font-size: 10px; font-weight: 700; color: #9CA3AF; text-transform: uppercase; letter-spacing: .7px; }
    /* Section */
    .section { margin-bottom: 32px; }
    .section-title { font-size: 10.5px; font-weight: 700; color: #9CA3AF; text-transform: uppercase; letter-spacing: 1px; border-bottom: 1px solid #E8EDF5; padding-bottom: 8px; margin-bottom: 16px; }
    /* Table */
    table { width: 100%; border-collapse: collapse; font-size: 12.5px; }
    th { background: #F8FAFF; padding: 9px 12px; text-align: left; font-size: 10px; font-weight: 700; color: #6B7280; text-transform: uppercase; letter-spacing: .5px; border-bottom: 1px solid #E8EDF5; }
    td { padding: 10px 12px; border-bottom: 1px solid #F4F6FA; vertical-align: middle; }
    tr:last-child td { border-bottom: none; }
    /* Bar */
    .bar-wrap { background: #F1F5F9; border-radius: 4px; height: 7px; overflow: hidden; width: 80px; display: inline-block; vertical-align: middle; }
    .bar-fill { height: 100%; border-radius: 4px; }
    /* Verdict chips */
    .chip { display: inline-block; padding: 2px 8px; border-radius: 5px; font-size: 10.5px; font-weight: 700; }
    .chip-pass { background: #DCFCE7; color: #166534; }
    .chip-flag { background: #FEF9C3; color: #854D0E; }
    .chip-reject { background: #FEE2E2; color: #991B1B; }
    /* AI section */
    .ai-box { background: linear-gradient(135deg, #EFF6FF, #F5F3FF); border: 1px solid #BFDBFE; border-radius: 12px; padding: 18px 20px; margin-bottom: 24px; }
    .ai-label { font-size: 10px; font-weight: 700; color: ${accent}; text-transform: uppercase; letter-spacing: 1px; margin-bottom: 8px; }
    .ai-text { font-size: 13px; color: #1E3A8A; line-height: 1.7; }
    .theme-pill { display: inline-block; background: white; border: 1px solid #BFDBFE; border-radius: 20px; padding: 3px 10px; font-size: 11px; color: #1E40AF; font-weight: 500; margin: 3px 3px 3px 0; }
    .quote-block { border-left: 3px solid ${accent}; background: #F8FAFF; border-radius: 0 8px 8px 0; padding: 10px 14px; margin-bottom: 8px; font-size: 12.5px; color: #374151; font-style: italic; line-height: 1.6; }
    /* IFI score */
    .ifi-row { display: flex; align-items: center; gap: 16px; }
    .ifi-score { font-size: 52px; font-weight: 800; color: ${accent}; line-height: 1; }
    .ifi-denom { font-size: 18px; color: #CBD5E1; }
    .ifi-desc { font-size: 12.5px; color: #6B7280; max-width: 360px; line-height: 1.6; }
    /* Verification statement */
    .verify-row { display: flex; align-items: center; gap: 10px; padding: 9px 0; border-bottom: 1px solid #F4F6FA; }
    .verify-row:last-child { border-bottom: none; }
    .verify-check { width: 22px; height: 22px; border-radius: 50%; background: #DCFCE7; display: flex; align-items: center; justify-content: center; flex-shrink: 0; font-size: 11px; }
    .verify-text { font-size: 13px; color: #374151; }
    /* Progress bar sections */
    .progress-row { display: flex; align-items: center; gap: 12px; margin-bottom: 12px; }
    .progress-label { font-size: 12px; color: #374151; width: 150px; flex-shrink: 0; }
    .progress-track { flex: 1; background: #F1F5F9; border-radius: 5px; height: 8px; overflow: hidden; }
    .progress-fill { height: 100%; border-radius: 5px; }
    .progress-pct { font-size: 11.5px; font-weight: 700; width: 36px; text-align: right; flex-shrink: 0; }
    /* Cert badge */
    .cert-badge { display: inline-flex; align-items: center; gap: 7px; border: 1px solid #BFDBFE; border-radius: 8px; padding: 7px 14px; font-size: 11.5px; font-weight: 700; color: ${accent}; background: #EFF6FF; }
    /* Footer */
    .footer { margin-top: 40px; padding-top: 18px; border-top: 1px solid #E8EDF5; display: flex; align-items: center; justify-content: space-between; }
    .footer-left { font-size: 11px; color: #9CA3AF; line-height: 1.6; }
    /* Print controls */
    .print-bar { position: fixed; top: 0; left: 0; right: 0; background: #0A1230; padding: 10px 24px; display: flex; align-items: center; justify-content: space-between; z-index: 100; }
    .print-bar span { font-size: 12px; font-weight: 600; color: rgba(255,255,255,.7); }
    .print-btn { background: ${accent}; color: white; border: none; border-radius: 7px; padding: 8px 20px; font-size: 13px; font-weight: 600; cursor: pointer; font-family: Inter, Arial, sans-serif; }
    @media print { .print-bar { display: none !important; } .wrap { padding-top: 0; } }
  `;

  const logoHtml = ctx.logoDataUrl
    ? `<img src="${ctx.logoDataUrl}" alt="${ctx.orgName}" style="height:40px;max-width:160px;object-fit:contain;display:block;margin-bottom:6px">`
    : `<div class="brand-name">FIELDSC<em>◉</em>RE <span style="color:#9CA3AF;font-weight:400;letter-spacing:1px;font-size:10px">· ResearchOS</span></div>`;

  const header = `
    <div class="page-header">
      <div>
        ${logoHtml}
        <div class="brand-tag">${ctx.orgName.toUpperCase()} · VERIFY · ANALYZE · DECIDE</div>
      </div>
      <div class="header-meta">
        <strong>${title}</strong>
        <span>${ctx.projectName}</span><br>
        <span>${ctx.orgName}</span><br>
        <span>Generated ${date}</span>
      </div>
    </div>`;

  const statBlock = `
    <div class="stats">
      <div class="stat"><div class="stat-value">${ctx.submissionCount.toLocaleString()}</div><div class="stat-label">Total Submissions</div></div>
      <div class="stat"><div class="stat-value" style="color:#059669">${passP}%</div><div class="stat-label">Pass Rate</div></div>
      <div class="stat"><div class="stat-value" style="color:#D97706">${flagP}%</div><div class="stat-label">Flagged</div></div>
      <div class="stat"><div class="stat-value" style="color:#DC2626">${rejectP}%</div><div class="stat-label">Rejected</div></div>
    </div>`;

  const aiBlock = () => {
    if (!ctx.aiSummary && !ctx.aiThemes?.length && !ctx.aiQuotes?.length) return '';
    return `
      <div class="ai-box">
        <div class="ai-label">◉ Ada AI Analysis</div>
        ${ctx.aiSummary ? `<div class="ai-text">${ctx.aiSummary}</div>` : ''}
        ${ctx.aiThemes?.length ? `<div style="margin-top:12px">${ctx.aiThemes.map(t => `<span class="theme-pill">${t}</span>`).join('')}</div>` : ''}
      </div>
      ${ctx.aiQuotes?.length ? `
        <div class="section">
          <div class="section-title">Voice of Respondent</div>
          ${ctx.aiQuotes.slice(0, 3).map(q => `<div class="quote-block">"${q}"</div>`).join('')}
        </div>` : ''}`;
  };

  const ifiBlock = () => {
    if (ctx.ifScore === undefined) return '';
    const color = ctx.ifScore >= 75 ? '#059669' : ctx.ifScore >= 55 ? '#D97706' : '#DC2626';
    const label = ctx.ifScore >= 75 ? 'Strong signal fidelity' : ctx.ifScore >= 55 ? 'Moderate fidelity — review flagged items' : 'Low fidelity — further QC recommended';
    return `
      <div class="section">
        <div class="section-title">Intent Fidelity Index (IFI)</div>
        <div class="ifi-row">
          <div><span class="ifi-score" style="color:${color}">${ctx.ifScore}</span><span class="ifi-denom">/100</span></div>
          <div class="ifi-desc">${label}. The IFI measures how well the collected responses reflect the research intent — signal quality, thematic consistency, and respondent engagement.</div>
        </div>
      </div>`;
  };

  const verificationStatement = `
    <div class="section">
      <div class="section-title">Verification Statement</div>
      ${[
        'GPS coordinates validated against approved survey boundaries',
        'Interview duration verified within acceptable range',
        'Audio recordings screened for two-voice conversation',
        'Photographs fingerprinted and duplicate-checked',
        'Duplicate submission detection applied across all submissions',
        'AI-generated content detection active',
      ].map(t => `<div class="verify-row"><div class="verify-check">✓</div><div class="verify-text">${t}</div></div>`).join('')}
    </div>`;

  const enumeratorTable = () => {
    const rows = ctx.enumeratorRows;
    if (!rows?.length) return '';
    const tableRows = rows.map(e => {
      const t = e.submissions || 1;
      const p = pct(e.pass, t);
      const tier = p >= 85 ? 'Excellent' : p >= 70 ? 'Good' : p >= 55 ? 'Needs coaching' : 'At risk';
      const tierColor = p >= 85 ? '#059669' : p >= 70 ? '#2463EB' : p >= 55 ? '#D97706' : '#DC2626';
      return `<tr>
        <td style="font-weight:600;color:#0A1230">${e.name}</td>
        <td>${e.submissions}</td>
        <td><span class="chip chip-pass">${e.pass}</span></td>
        <td><span class="chip chip-flag">${e.flag}</span></td>
        <td><span class="chip chip-reject">${e.reject}</span></td>
        <td>
          <div class="bar-wrap"><div class="bar-fill" style="width:${p}%;background:${tierColor}"></div></div>
          <span style="margin-left:8px;font-size:11.5px;font-weight:700;color:${tierColor}">${p}%</span>
        </td>
        <td style="color:${tierColor};font-weight:700;font-size:11.5px">${tier}</td>
      </tr>`;
    }).join('');
    return `
      <div class="section">
        <div class="section-title">Enumerator Scorecards</div>
        <table>
          <thead><tr><th>Enumerator</th><th>Submissions</th><th>Pass</th><th>Flag</th><th>Reject</th><th>Pass Rate</th><th>Verdict</th></tr></thead>
          <tbody>${tableRows}</tbody>
        </table>
      </div>`;
  };

  const engineTable = () => {
    const rows = ctx.engineRows;
    if (!rows?.length) return '';
    const tableRows = rows.map(e => {
      const t = e.total || 1;
      const p = pct(e.pass, t);
      return `<tr>
        <td style="font-weight:600">${e.name}</td>
        <td><div class="progress-track" style="width:100%"><div class="progress-fill" style="width:${p}%;background:#059669"></div></div></td>
        <td style="color:#059669;font-weight:700">${p}%</td>
        <td style="color:#D97706">${pct(e.flag, t)}%</td>
        <td style="color:#DC2626">${pct(e.reject, t)}%</td>
      </tr>`;
    }).join('');
    return `
      <div class="section">
        <div class="section-title">Engine Verification Breakdown</div>
        <table>
          <thead><tr><th>Verification Engine</th><th>Distribution</th><th>Pass</th><th>Flag</th><th>Reject</th></tr></thead>
          <tbody>${tableRows}</tbody>
        </table>
      </div>`;
  };

  const qualityStatement = passP >= 80
    ? `<div style="background:#F0FDF4;border:1px solid #BBF7D0;border-radius:10px;padding:14px 18px;margin-bottom:24px;font-size:13px;color:#166534;font-weight:600">✓ This dataset meets standard research quality thresholds and is suitable for analysis, reporting, and client delivery.</div>`
    : flagP > 20
    ? `<div style="background:#FFFBEB;border:1px solid #FDE68A;border-radius:10px;padding:14px 18px;margin-bottom:24px;font-size:13px;color:#854D0E;font-weight:600">⚠ A significant proportion of submissions were flagged for review. Resolve open flags before final analysis.</div>`
    : `<div style="background:#FEF2F2;border:1px solid #FECACA;border-radius:10px;padding:14px 18px;margin-bottom:24px;font-size:13px;color:#991B1B;font-weight:600">⚠ Rejection rate is above threshold. A targeted re-collection exercise is recommended for affected areas.</div>`;

  const footer = `
    <div class="footer">
      <div class="footer-left">
        Verified by <strong>${ctx.generatedBy}</strong> · ${ctx.orgName}<br>
        ${footerText}
      </div>
      <div class="cert-badge" style="background:${accent}11;border-color:${accent}44;color:${accent}">◉ FieldScore Verified · ${passN.toLocaleString()}/${ctx.submissionCount.toLocaleString()} submissions</div>
    </div>`;

  // ── Per-report body ─────────────────────────────────────────────────────────

  let body = '';

  if (reportId === 'executive' || reportId === 'client') {
    body = `
      <div class="title-block">
        <div class="report-label">${title}</div>
        <h1>${ctx.projectName}</h1>
        <div class="subtitle">Prepared by ${ctx.orgName} · FieldScore verified · ${date}</div>
      </div>
      ${qualityStatement}
      ${statBlock}
      ${aiBlock()}
      ${ifiBlock()}
      <div class="section">
        <div class="section-title">Key Findings</div>
        <p style="margin-bottom:10px;font-size:13px;color:#374151">
          This dataset passed FieldScore's multi-engine QC process with a <strong>${passP}% pass rate</strong> across
          <strong>${ctx.submissionCount.toLocaleString()} submissions</strong>${ctx.enumeratorRows?.length ? ` collected by <strong>${ctx.enumeratorRows.length} enumerators</strong>` : ''}.
          ${rejectP > 0 ? `${rejectP}% of submissions were rejected and excluded from the clean dataset.` : 'No submissions were rejected.'}
        </p>
        ${flagP > 0 ? `<p style="font-size:13px;color:#374151">${flagP}% of submissions were flagged for manual review and resolved by field supervisors before inclusion in the final dataset.</p>` : ''}
      </div>
      ${verificationStatement}
      ${enumeratorTable()}`;
  } else if (reportId === 'technical') {
    body = `
      <div class="title-block">
        <div class="report-label">${title}</div>
        <h1>${ctx.projectName}</h1>
        <div class="subtitle">${ctx.orgName} · ${date}</div>
      </div>
      ${statBlock}
      ${engineTable()}
      ${enumeratorTable()}
      ${ifiBlock()}
      ${verificationStatement}`;
  } else if (reportId === 'enumerator') {
    body = `
      <div class="title-block">
        <div class="report-label">${title}</div>
        <h1>${ctx.projectName}</h1>
        <div class="subtitle">${ctx.orgName} · ${date}</div>
      </div>
      ${statBlock}
      ${enumeratorTable()}
      ${aiBlock()}`;
  }

  return `<!DOCTYPE html>
<html lang="en"><head>
<meta charset="utf-8">
<title>${title} — ${ctx.projectName}</title>
<style>${css}</style>
</head><body>
<div class="print-bar">
  <span>${title} — ${ctx.projectName}</span>
  <button class="print-btn" onclick="window.print()">Print / Save as PDF</button>
</div>
<div class="wrap">
  ${header}
  ${body}
  ${footer}
</div>
</body></html>`;
}
